services:
  oracle-db:
    ports:
      - '1521:1521'
    container_name: oracle
    image: gvenzl/oracle-free:slim
    environment:
      ORACLE_PASSWORD: SuperSecret0
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s