services:
  oracle-db:
    ports:
      - '1521:1521'
    container_name: oracle
    image: gvenzl/oracle-free:slim
    environment:
      ORACLE_PASSWORD: SuperSecret0
      APP_USER: tareas
      APP_USER_PASSWORD: S3cr3t0
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.4
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - '8081:8080'
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
    keycloak_data: