CREATE USER tareas IDENTIFIED BY S3cr3t0;
GRANT ALL PRIVILEGES TO tareas;


CREATE TABLE tareas.app_roles (
                                  id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                  nombre_rol VARCHAR2(60 CHAR) NOT NULL UNIQUE,
                                  f_creacion TIMESTAMP,
                                  f_modificacion TIMESTAMP
);


ALTER TABLE tareas.app_roles
    ADD CONSTRAINT pk_app_roles PRIMARY KEY (id_rol);


CREATE TABLE tareas.app_tareas (
                                   id_tarea INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                   estado INTEGER CHECK ((estado >= 0) AND (estado <= 100)),
                                   id_usuario INTEGER,
                                   color VARCHAR2(50 CHAR),
                                   nombre VARCHAR2(200 CHAR) NOT NULL,
                                   f_creacion TIMESTAMP,
                                   f_modificacion TIMESTAMP
);


ALTER TABLE tareas.app_tareas
    ADD CONSTRAINT pk_app_tareas PRIMARY KEY (id_tarea);


CREATE TABLE tareas.app_usuarios (
                                     id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                     nombre_apellidos VARCHAR2(200 CHAR),
                                     iniciales VARCHAR2(10 CHAR),
                                     correo_electronico VARCHAR2(100 CHAR) NOT NULL UNIQUE,
                                     contrasena VARCHAR2(100 CHAR) NOT NULL,
                                     f_creacion TIMESTAMP(6),
                                     f_modificacion TIMESTAMP(6)
);

ALTER TABLE tareas.app_usuarios
    ADD CONSTRAINT pk_app_usuarios PRIMARY KEY (id_usuario);


CREATE TABLE tareas.app_usuarios_roles (
                                           id_rol INTEGER NOT NULL,
                                           id_usuario INTEGER NOT NULL
);

ALTER TABLE tareas.app_usuarios_roles
    ADD CONSTRAINT pk_app_usuarios_roles PRIMARY KEY (id_rol, id_usuario);



ALTER TABLE tareas.app_tareas
    ADD CONSTRAINT fk_tareas_usuario
        FOREIGN KEY (id_usuario)
            REFERENCES tareas.app_usuarios (id_usuario);

ALTER TABLE tareas.app_usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_rol
        FOREIGN KEY (id_rol)
            REFERENCES tareas.app_roles (id_rol);

ALTER TABLE tareas.app_usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_usuario
        FOREIGN KEY (id_usuario)
            REFERENCES tareas.app_usuarios (id_usuario);

ALTER SESSION SET CURRENT_SCHEMA = tareas;

-- Insertar datos
INSERT INTO app_roles (nombre_rol, f_creacion)
VALUES ('BASE', SYSTIMESTAMP);

-- Insertar rol ADMINISTRADOR
INSERT INTO app_roles (nombre_rol, f_creacion)
VALUES ('ADMINISTRADOR', SYSTIMESTAMP);

-- Insertar usuario demo
INSERT INTO app_usuarios (nombre_apellidos, correo_electronico, contrasena, f_creacion)
VALUES ('Usuario demo', 'formacion@eclap.jcyl.es', 'CambiaLaClaveYa!', SYSTIMESTAMP);

-- Asociar roles al usuario (asumiendo IDs generados: 1 para BASE, 2 para ADMINISTRADOR, 1 para usuario)
INSERT INTO app_usuarios_roles (id_rol, id_usuario)
VALUES (1, 1);

INSERT INTO app_usuarios_roles (id_rol, id_usuario)
VALUES (2, 1);

-- Confirmar las inserciones
COMMIT;